version: "3"

services:
  redis:
    container_name: umschool-redis
    image: redis
    ports:
      - "6379:6379"

  celery:
    container_name: umschool-celery
    build:
      context: umschool
    entrypoint: celery
    command: -A umschool worker -l info
    environment:
      REDIS_URI: "redis://umschool-redis:6379/0"
    depends_on:
      - redis

  server:
    container_name: umschool-server
    build:
      context: umschool
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      REDIS_URI: "redis://umschool-redis:6379/0"
    depends_on:
      - celery
      - redis

