version: "3"

services:
  pgdb:
    image: postgres
    env_file:
      - .env
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

  redis:
    image: redis:7.0.15-alpine3.20
    ports:
      - "6379:6379"

  celery:
    build:
      context: umschool
    entrypoint: celery
    command: -A umschool worker -l info
    env_file:
      - .env
    depends_on:
      - redis
      - pgdb

  test:
    build:
      context: umschool
    command: python manage.py test
    env_file:
      - .env

    depends_on:
      - celery
      - redis
      - pgdb

  server:
    build:
      context: umschool
    restart: unless-stopped
    command: >
      sh -c "./entrypoint.sh"
    ports:
      - "80:8000"
    env_file:
      - .env

    depends_on:
      - celery
      - redis
      - pgdb

volumes:
  pgdbdata: null
