# Generated by Django 5.0.3 on 2024-06-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teacher",
            options={"verbose_name": "Учитель", "verbose_name_plural": "Учителя"},
        ),
        migrations.AddField(
            model_name="student",
            name="last_name",
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="surname",
            field=models.CharField(max_length=75, null=True),
        ),
    ]
