# Generated by Django 4.2.1 on 2023-12-31 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('source_code', models.FileField(upload_to='')),
                ('is_accepted', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Решение',
                'verbose_name_plural': 'Решения',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('input_data', models.TextField()),
                ('output_data', models.TextField()),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('solutions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.solution')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.AddField(
            model_name='solution',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.task'),
        ),
    ]
