# Generated by Django 4.2.1 on 2023-12-31 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='solutions',
        ),
        migrations.AddField(
            model_name='solution',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='surname',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
