# Generated by Django 4.2.1 on 2023-12-31 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_student_solutions_solution_student_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='task_id',
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Tests',
        ),
    ]
