# Generated by Django 4.2.1 on 2023-12-31 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('python_code_check_system', '0001_initial'), ('python_code_check_system', '0002_alter_student_solutions_alter_task_tests'), ('python_code_check_system', '0003_alter_solution_task_id_alter_student_solutions_and_more'), ('python_code_check_system', '0004_alter_solution_source_code'), ('python_code_check_system', '0005_remove_student_solutions_remove_task_tests_and_more'), ('python_code_check_system', '0006_initial'), ('python_code_check_system', '0007_task_complexity')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75, null=True)),
                ('surname', models.CharField(max_length=75, null=True)),
                ('last_name', models.CharField(max_length=75, null=True)),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('complexity', models.CharField(max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('input_data', models.TextField()),
                ('output_data', models.TextField()),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='python_code_check_system.task')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('source_code', models.FileField(upload_to='')),
                ('is_accepted', models.BooleanField()),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='python_code_check_system.student')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='python_code_check_system.task')),
            ],
            options={
                'verbose_name': 'Решение',
                'verbose_name_plural': 'Решения',
            },
        ),
    ]
