# Generated by Django 4.2.1 on 2023-12-30 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('source_code', models.TextField()),
                ('is_accepted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('input_data', models.TextField()),
                ('output_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('tests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='python_code_check_system.tests')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('solutions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='python_code_check_system.solution')),
            ],
        ),
        migrations.AddField(
            model_name='solution',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='python_code_check_system.task', unique=True),
        ),
    ]
