# Generated by Django 4.2.1 on 2024-01-03 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_check_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tests',
            new_name='Test',
        ),
    ]
