# Generated by Django 5.0.9 on 2025-09-13 21:50

from django.db import migrations, models
import django.utils.timezone
from django.db import models as models_deletion


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_check_system', '0001_initial'),
    ]

    operations = [
        # Добавляем поля в модель Solution
        migrations.AddField(
            model_name='solution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        # Изменяем related_name для student
        migrations.AlterField(
            model_name='solution',
            name='student',
            field=models.ForeignKey(
                null=True, on_delete=models.CASCADE, related_name='solutions', to='account_service.student'
            ),
        ),
        # Изменяем on_delete для task
        migrations.AlterField(
            model_name='solution',
            name='task',
            field=models.ForeignKey(on_delete=models.CASCADE, to='python_code_check_system.task'),
        ),
        # Добавляем поля в модель Task
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активно ли задание'),
        ),
        # Изменяем поле complexity на choices
        migrations.AlterField(
            model_name='task',
            name='complexity',
            field=models.CharField(
                choices=[('easy', 'Легкое'), ('medium', 'Среднее'), ('hard', 'Сложное')],
                default='easy',
                help_text='Уровень сложности задания',
                max_length=10,
            ),
        ),
        # Добавляем поля в модель Test
        migrations.AddField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        # Изменяем related_name для task в Test
        migrations.AlterField(
            model_name='test',
            name='task',
            field=models.ForeignKey(on_delete=models.CASCADE, related_name='tests', to='python_code_check_system.task'),
        ),
        # Добавляем индексы
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['student', 'task'], name='python_code_solution_student_task_idx'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['is_accepted'], name='python_code_solution_is_accepted_idx'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['created_at'], name='python_code_solution_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_active'], name='python_code_task_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['complexity'], name='python_code_task_complexity_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_at'], name='python_code_task_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['task'], name='python_code_test_task_idx'),
        ),
    ]
