# Generated by Django 4.2.1 on 2023-12-30 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_check_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='solutions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='python_code_check_system.solution', unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='tests',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='python_code_check_system.tests', unique=True),
        ),
    ]
