# Generated by Django 4.2.1 on 2023-12-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_check_system', '0003_alter_solution_task_id_alter_student_solutions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='source_code',
            field=models.FileField(upload_to=''),
        ),
    ]
