# Generated by Django 5.0.1 on 2024-04-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("python_code_check_system", "0003_alter_solution_is_accepted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solution",
            name="source_code",
            field=models.TextField(),
        ),
    ]
