# Generated by Django 5.0.3 on 2024-05-17 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("python_code_check_system", "0004_alter_solution_source_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="solution",
            old_name="student_id",
            new_name="student",
        ),
        migrations.RenameField(
            model_name="solution",
            old_name="task_id",
            new_name="task",
        ),
        migrations.RenameField(
            model_name="test",
            old_name="task_id",
            new_name="task",
        ),
    ]
