# Generated by Django 4.2.1 on 2023-12-31 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_check_system', '0004_alter_solution_source_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='solutions',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tests',
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Tests',
        ),
    ]
