# Generated by Django 4.2.1 on 2023-12-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_check_system', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complexity',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
