name: Core tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r umschool/requirements.txt
    - name: Test stdin/stdout
      run: |
        cd umschool/
        pytest python_code_check_system/check_system/tests/test_stdin_stdout.py

    - name: Test class
      run: |
        cd umschool/
        pytest python_code_check_system/check_system/tests/test_class.py
