name: Core System Tests

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

permissions:
  contents: read

jobs:
  core-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r umschool/requirements.txt
    
    - name: Test stdin/stdout functionality
      run: |
        cd umschool/
        pytest python_code_check_system/check_system/tests/test_stdin_stdout.py -v

    - name: Test class functionality
      run: |
        cd umschool/
        pytest python_code_check_system/check_system/tests/test_class.py -v

    - name: Check memory example syntax
      run: |
        python -m py_compile poc/memory.py

    - name: Check timeout example syntax
      run: |
        python -m py_compile poc/timeout.py

    - name: Test core system integration
      run: |
        cd umschool/
        python -c "
        from python_code_check_system.check_system.core import CodeChecker
        from python_code_check_system.check_system.types import TestCase
        
        # Test basic functionality
        checker = CodeChecker()
        test_case = TestCase(input_data='5\n3', output_data='8')
        
        result = checker.check_code('a = int(input())\nb = int(input())\nprint(a + b)', [test_case])
        print(f'Test result: {result.verdict}')
        print(f'Test passed: {result.verdict}')
        "
