name: Deploy

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        source: "."
        target: "/home/${{ secrets.USERNAME }}/python-code-check-system"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          set -e
          echo "🚀 Начинаем деплой Python Code Check System..."
          
          cd python-code-check-system/
          
          # Обновляем дату релиза в шаблоне
          echo "📅 Обновляем дату релиза..."
          date=$(git log --pretty=format:"%ad" --date=format:"%d.%m.%Y %H:%M" -n 1)
          search="RELEASE_DATE_TEMPLATE"
          filename="./umschool/templates/python_code_check_system/base.html"
          if [ -f "$filename" ]; then
            sed -i "s/$search/$date/" $filename
            echo "✅ Дата релиза обновлена: $date"
          else
            echo "⚠️ Файл шаблона не найден, пропускаем обновление даты"
          fi
          
          # Проверяем наличие .env файла
          if [ ! -f ".env" ]; then
            echo "📝 Создаем .env файл из примера..."
            cp env.example .env
            echo "✅ .env файл создан"
          fi
          
          # Создаем необходимые директории
          echo "📁 Создаем необходимые директории..."
          mkdir -p umschool/media umschool/staticfiles
          echo "✅ Директории созданы"
          
          # Останавливаем старые контейнеры
          echo "🛑 Останавливаем старые контейнеры..."
          docker compose down || true
          
          # Собираем новые образы
          echo "🔨 Собираем новые Docker образы..."
          docker compose build --no-cache
          
          # Запускаем сервисы
          echo "🚀 Запускаем сервисы..."
          docker compose up -d
          
          # Ждем готовности сервисов
          echo "⏳ Ждем готовности сервисов..."
          sleep 30
          
          # Проверяем статус контейнеров
          echo "📊 Статус контейнеров:"
          docker compose ps
          
          # Проверяем что Nginx запустился
          echo "🌐 Проверяем Nginx..."
          if ! docker compose ps | grep -q "nginx.*Up"; then
            echo "❌ Nginx не запустился"
            docker compose logs nginx
            exit 1
          else
            echo "✅ Nginx запущен"
          fi
          
          # Проверяем здоровье сервисов
          echo "🏥 Проверяем здоровье сервисов..."
          if docker compose exec -T server python manage.py check --deploy; then
            echo "✅ Django проверка прошла успешно"
          else
            echo "❌ Ошибка в Django конфигурации"
            docker compose logs server
            exit 1
          fi
          
          # Собираем статические файлы
          echo "📁 Собираем статические файлы..."
          docker compose exec -T server python manage.py collectstatic --noinput
          
          # Настраиваем Nginx если не настроен
          echo "🌐 Проверяем Nginx..."
          if ! systemctl is-active --quiet nginx; then
            echo "🔧 Настраиваем Nginx..."
            if [ -f "nginx.conf" ] && [ -f "setup-nginx.sh" ]; then
              chmod +x setup-nginx.sh
              sudo ./setup-nginx.sh
            else
              echo "⚠️ Файлы Nginx не найдены, пропускаем настройку"
            fi
          else
            echo "✅ Nginx уже настроен"
          fi
          
          # Финальная проверка
          echo "🔍 Финальная проверка..."
          if curl -f http://localhost:8000/ > /dev/null 2>&1; then
            echo "✅ Сайт доступен через Nginx"
          else
            echo "❌ Сайт недоступен через Nginx"
            docker compose logs nginx
            docker compose logs server
            exit 1
          fi
          
          echo "🎉 Деплой завершен успешно!"
          echo "🌐 Сайт доступен по адресу: http://${{ secrets.HOST }}:8000"
