name: Django tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Copy env file
      run: cp env.example .env

    - name: Run tests
      run: docker compose up -d

    - name: Check services
      run: |
        docker-compose ps

