name: Django Tests

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Copy env file
      run: cp env.example .env

    - name: Configure database for tests
      run: |
        # Use SQLite for tests to avoid PostgreSQL connection issues
        echo "DATABASE_URL=sqlite:///db.sqlite3" > .env

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r umschool/requirements.txt

    - name: Run Django migrations
      run: |
        cd umschool/
        python manage.py migrate --settings=umschool.settings

    - name: Run all Django tests
      run: |
        cd umschool/
        python manage.py test --settings=umschool.settings --verbosity=2

    - name: Run model tests
      run: |
        cd umschool/
        python manage.py test python_code_check_system.test_files.test_models --settings=umschool.settings --verbosity=2

    - name: Run form tests
      run: |
        cd umschool/
        python manage.py test python_code_check_system.test_files.test_forms --settings=umschool.settings --verbosity=2

    - name: Run view tests
      run: |
        cd umschool/
        python manage.py test python_code_check_system.test_files.test_views --settings=umschool.settings --verbosity=2

    - name: Run core system tests
      run: |
        cd umschool/
        python manage.py test python_code_check_system.check_system.tests --settings=umschool.settings --verbosity=2

    - name: Run main tests
      run: |
        cd umschool/
        python manage.py test python_code_check_system.tests --settings=umschool.settings --verbosity=2

    - name: Test coverage
      run: |
        cd umschool/
        pip install coverage
        coverage run --source='.' manage.py test --settings=umschool.settings
        coverage report
        coverage html

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./umschool/htmlcov/coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
