name: Code Quality & Flake8

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install black
        pip install isort
        pip install -r umschool/requirements.txt
    
    - name: Run Flake8
      run: |
        flake8 $(git ls-files '*.py')
    
    - name: Check code formatting with Black
      run: |
        black --check $(git ls-files '*.py')
    
    - name: Check import sorting with isort
      run: |
        isort --check-only $(git ls-files '*.py')
    
    - name: Security check with bandit
      run: |
        pip install bandit
        bandit -r umschool/ -f json -o bandit-report.json || true
        bandit -r umschool/ -f txt
