name: Security Scan

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  schedule:
    - cron: '0 3 * * 1'  # Run every Monday at 3 AM

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install security tools
      run: |
        python -m pip install --upgrade pip
        pip install bandit
        pip install safety
        pip install semgrep
        pip install -r umschool/requirements.txt

    - name: Run Bandit security scan
      run: |
        bandit -r umschool/ -f json -o bandit-report.json || true
        bandit -r umschool/ -f txt

    - name: Check for known security vulnerabilities
      run: |
        safety check --json --output safety-report.json || true
        safety check

    - name: Run Semgrep security scan
      run: |
        semgrep --config=auto umschool/ --json --output=semgrep-report.json || true
        semgrep --config=auto umschool/

    - name: Check Django security settings
      run: |
        cd umschool/
        python manage.py check --deploy --settings=umschool.settings

    - name: Check for hardcoded secrets
      run: |
        grep -r "password\|secret\|key\|token" umschool/ --include="*.py" | grep -v "test" | grep -v "example" || echo "No hardcoded secrets found"

    - name: Upload security reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: security-reports
        path: |
          bandit-report.json
          safety-report.json
          semgrep-report.json
